# Generated by Django 4.0.5 on 2022-06-28 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('religion', models.CharField(choices=[('RO', 'RomanCatholic'), ('OR', 'Orthodox'), ('JU', 'Judaism'), ('OT', 'Other')], max_length=2)),
                ('open_for_prayer', models.BooleanField()),
                ('open_for_visitors', models.BooleanField()),
                ('closed', models.BooleanField()),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), size=None)),
            ],
        ),
    ]
