# Generated by Django 4.0.5 on 2022-08-03 11:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0003_delete_placeofprayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('purpose', models.CharField(choices=[('PP', 'PlaceOfPrayer'), ('CL', 'Cloister'), ('AD', 'Administration'), ('OT', 'Other')], max_length=2)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('owner', models.TextField()),
                ('religion', models.CharField(choices=[('RO', 'RomanCatholic'), ('OR', 'Orthodox'), ('JU', 'Judaism'), ('OT', 'Other')], max_length=2)),
                ('visitors_access', models.CharField(choices=[('UR', 'Unrestricted'), ('SR', 'SomeRestrictions'), ('NA', 'NoAccess')], max_length=2)),
                ('visitors_access_details', models.TextField()),
                ('praying_access', models.BooleanField()),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None), size=None)),
            ],
        ),
    ]
