# Generated by Django 4.0.5 on 2022-08-04 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0005_green'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
