# Generated by Django 4.0.5 on 2022-08-04 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0007_building_plot_green_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=500), size=None),
        ),
        migrations.AlterField(
            model_name='green',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=500), size=None), size=None),
        ),
        migrations.AlterField(
            model_name='plot',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(max_length=500), size=None), size=None),
        ),
    ]
