# Generated by Django 4.0.5 on 2022-08-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0008_alter_building_coordinates_alter_green_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='owneership_type',
            field=models.CharField(choices=[('PP', 'KrakowPlacedInPossession'), ('JO', 'KrakowJoinedOwnership'), ('PU', 'KrakowPerpetualUse'), ('FI', 'Fisc'), ('CP', 'CountyPlacedInPossession'), ('CO', 'CountyJoinedOwnership'), ('CU', 'CountyPerpetualUse'), ('VO', 'Voivodeship'), ('NP', 'NaturalPerson'), ('LE', 'LegalEntity')], default='LE', max_length=2),
            preserve_default=False,
        ),
    ]
