# Generated by Django 4.0.5 on 2022-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0010_rename_owneership_type_plot_ownership_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='green',
            name='green_type',
            field=models.CharField(choices=[('GD', 'Garden'), ('PK', 'Park'), ('MD', 'Meadow'), ('SQ', 'Square'), ('CT', 'Cemetery')], max_length=2),
        ),
    ]
