# Generated by Django 4.0.5 on 2022-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0011_alter_green_green_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='visitors_access',
            field=models.CharField(choices=[('UR', 'Unrestricted'), ('OD', 'OpenDuringDaytime'), ('SR', 'SomeRestrictions'), ('NA', 'NoAccess')], max_length=2),
        ),
        migrations.AlterField(
            model_name='green',
            name='visitors_access',
            field=models.CharField(choices=[('UR', 'Unrestricted'), ('OD', 'OpenDuringDaytime'), ('SR', 'SomeRestrictions'), ('NA', 'NoAccess')], max_length=2),
        ),
        migrations.AlterField(
            model_name='plot',
            name='visitors_access',
            field=models.CharField(choices=[('UR', 'Unrestricted'), ('OD', 'OpenDuringDaytime'), ('SR', 'SomeRestrictions'), ('NA', 'NoAccess')], max_length=2),
        ),
    ]
