# Generated by Django 4.0.5 on 2022-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0012_alter_building_visitors_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='visitors_access',
            field=models.CharField(choices=[('UR', 'Unrestricted'), ('OD', 'OpenDuringDaytime'), ('SA', 'SpecialAccess'), ('NA', 'NoAccess')], max_length=2),
        ),
        migrations.AlterField(
            model_name='green',
            name='visitors_access',
            field=models.CharField(choices=[('UR', 'Unrestricted'), ('OD', 'OpenDuringDaytime'), ('SA', 'SpecialAccess'), ('NA', 'NoAccess')], max_length=2),
        ),
        migrations.AlterField(
            model_name='plot',
            name='visitors_access',
            field=models.CharField(choices=[('UR', 'Unrestricted'), ('OD', 'OpenDuringDaytime'), ('SA', 'SpecialAccess'), ('NA', 'NoAccess')], max_length=2),
        ),
    ]
