# Generated by Django 4.0.5 on 2022-08-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0016_alter_plot_ownership_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='ownership_model',
            field=models.CharField(choices=[('KP', 'KrakowProperty'), ('PP', 'KrakowPlacedInPossession'), ('JO', 'KrakowJoinedOwnership'), ('PU', 'KrakowPerpetualUse'), ('FI', 'Fisc'), ('CP', 'CountyPlacedInPossession'), ('CO', 'CountyJoinedOwnership'), ('CU', 'CountyPerpetualUse'), ('VO', 'Voivodeship'), ('NP', 'NaturalPerson'), ('LE', 'LegalEntity'), ('NL', 'NaturalAndLegalPerson')], max_length=2),
        ),
    ]
