# Generated by Django 4.0.5 on 2022-11-09 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0017_alter_plot_ownership_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('source', models.TextField()),
            ],
        ),
    ]
