# Generated by Django 4.0.5 on 2022-11-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0018_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageToProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.green')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.image')),
                ('plot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.plot')),
            ],
        ),
    ]
