# Generated by Django 4.0.5 on 2022-11-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0019_imagetoproperty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetoproperty',
            old_name='green_id',
            new_name='green',
        ),
        migrations.RenameField(
            model_name='imagetoproperty',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='imagetoproperty',
            old_name='plot_id',
            new_name='plot',
        ),
    ]
