# Generated by Django 4.0.5 on 2022-11-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0020_rename_green_id_imagetoproperty_green_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetoproperty',
            name='green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.green'),
        ),
        migrations.AlterField(
            model_name='imagetoproperty',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.plot'),
        ),
    ]
