# Generated by Django 4.0.5 on 2022-11-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0022_image_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetoproperty',
            name='main_image_for_green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_image_for_green', to='churchy.green'),
        ),
        migrations.AddField(
            model_name='imagetoproperty',
            name='main_image_for_plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_image_for_plot', to='churchy.plot'),
        ),
        migrations.AlterField(
            model_name='imagetoproperty',
            name='green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_green', to='churchy.green'),
        ),
        migrations.AlterField(
            model_name='imagetoproperty',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_plot', to='churchy.plot'),
        ),
    ]
