# Generated by Django 4.0.5 on 2022-11-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0023_imagetoproperty_main_image_for_green_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetoproperty',
            name='main_image_for_green',
        ),
        migrations.RemoveField(
            model_name='imagetoproperty',
            name='main_image_for_plot',
        ),
        migrations.AddField(
            model_name='image',
            name='high_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagetoproperty',
            name='green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.green'),
        ),
        migrations.AlterField(
            model_name='imagetoproperty',
            name='plot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churchy.plot'),
        ),
    ]
