# Generated by Django 4.0.5 on 2022-11-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churchy', '0024_remove_imagetoproperty_main_image_for_green_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='high_quality',
            new_name='aerial',
        ),
    ]
